server:
  port: 8080
  max-http-header-size: 16384

spring:
  application:
    name: url-shortener-api
  datasource:
    url: jdbc:postgresql://localhost:5432/url_shortener_db
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      pool-name: ShortenerHikariCP
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

jwt:
  # Base64 encoded secret key (min 256-bit)
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration-ms: 86400000 # 24 Hours

app:
  base-url: http://localhost:8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always