spring.application.name=backend


#
#spring.datasource.url=postgresql://db_user:WnKf5mzJULP4VyFkGbXz4oJdvcy3z4Eu@dpg-daijcrfqj5pc73ac2960-a.oregon-postgres.render.com/url_shortener_db_7bqo
#spring.datasource.username=db_user
#spring.datasource.password=WnKf5mzJULP4VyFkGbXz4oJdvcy3z4Eu
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true